### ISSUE TITLE
Max configs is not working

### ISSUE THREAD

**Issue by OlgaPaw** [antiagainst/codeclimate-cppcheck#19]
Hi, Here is my .codeclimate.yml
```
engines:
  cppcheck:
    enabled: true
    config:
      check: all
      stds:
        - c++11
      max_configs: 42
```

And output:
```
== src/main.c (2 issues) ==
0: Too many #ifdef configurations - cppcheck only checks 12 of 290 configurations. Use --force to check all configurations. 
```
